const STORAGE_KEY="brosplit_acid_v1";
let state=JSON.parse(localStorage.getItem(STORAGE_KEY))||{events:[],activeEventId:null,view:"events"};
const app=document.getElementById("app"),modal=document.getElementById("modal"),modalBody=document.getElementById("modalBody");
const posters=["🌴","🚗","💀","🍔","🍺","🔥","🧾","🎂","✈️","🏔️"];
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function money(n){return Math.round(Number(n||0)).toLocaleString("ru-RU")+" ₽"}
function safe(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function css(s){return String(s).replace(/\\/g,"\\\\").replace(/"/g,'\\"')}
function parseNames(t){return[...new Set(t.split(/[\n,;]+/g).map(x=>x.trim()).filter(Boolean))]}
function currentEvent(){return state.events.find(e=>e.id===state.activeEventId)||state.events[0]||null}
function showModal(html){modalBody.innerHTML=html;modal.classList.remove("hidden")}
function closeModal(){modal.classList.add("hidden");modalBody.innerHTML=""}
function openNewEventModal(){showModal(`<h2 class="form-title">Новое мероприятие</h2><label>Название</label><input id="eventTitle" placeholder="Пятница, ДР, Грузия..."/><label>Участники через запятую или с новой строки</label><textarea id="eventPeople" placeholder="Рома, Паша, Артем"></textarea><button class="acid-btn big" onclick="createEventFromModal()">Создать</button>`)}
function createEventFromModal(){const title=document.getElementById("eventTitle").value.trim(),people=parseNames(document.getElementById("eventPeople").value);if(!title)return alert("Название мероприятия обязательно.");const e={id:uid(),title,people,poster:posters[state.events.length%posters.length],expenses:[],createdAt:new Date().toISOString()};state.events.unshift(e);state.activeEventId=e.id;state.view="events";save();closeModal();render()}
function openEvent(id){state.activeEventId=id;state.view="expenses";save();render()}
function openAddExpenseModal(){const e=currentEvent();if(!e)return alert("Сначала создай мероприятие.");if(!e.people.length)return alert("Добавь участников.");const payers=e.people.map(n=>`<label class="payer-row"><input type="checkbox" data-payer-check="${safe(n)}"/><span>${safe(n)}</span><input type="number" data-paid="${safe(n)}" placeholder="₽"/></label>`).join("");const parts=e.people.map(n=>`<label class="split-option"><input type="checkbox" data-participant="${safe(n)}" checked/><div><strong>${safe(n)}</strong><small>участвует</small></div></label>`).join("");const fixed=e.people.map(n=>`<label class="payer-row"><input type="checkbox" data-fixed-check="${safe(n)}"/><span>${safe(n)}</span><input type="number" data-fixed="${safe(n)}" placeholder="фикс"/></label>`).join("");const custom=e.people.map(n=>`<label class="payer-row"><span></span><span>${safe(n)}</span><input type="number" data-custom="${safe(n)}" placeholder="доля"/></label>`).join("");showModal(`<h2 class="form-title">Добавить расход</h2><label>Название</label><input id="expenseTitle" placeholder="Макдак"/><label>Сумма</label><input id="expenseAmount" type="number" placeholder="3500"/><label>Кто оплатил</label><div class="pill-list">${payers}</div><label>Кто участвовал</label><div class="pill-list">${parts}</div><label>Как делить?</label><div class="pill-list"><label class="split-option"><input type="radio" name="splitMode" value="equal" checked onchange="refreshSplitDetails()"/><div><strong>Поровну</strong><small>Каждый платит одинаково</small></div></label><label class="split-option"><input type="radio" name="splitMode" value="fixed_rest" onchange="refreshSplitDetails()"/><div><strong>Фиксированные суммы + остаток поровну</strong><small>Дима 1500, остальные делят остаток</small></div></label><label class="split-option"><input type="radio" name="splitMode" value="custom" onchange="refreshSplitDetails()"/><div><strong>Своя сумма каждому</strong><small>Ручной режим</small></div></label></div><div id="fixedDetails" class="hidden"><label>Фиксированные суммы</label><div class="pill-list">${fixed}</div></div><div id="customDetails" class="hidden"><label>Своя сумма каждому</label><div class="pill-list">${custom}</div></div><button class="acid-btn big" onclick="addExpenseFromModal()">Сохранить расход</button>`)}
function refreshSplitDetails(){const m=document.querySelector("input[name='splitMode']:checked")?.value;document.getElementById("fixedDetails")?.classList.toggle("hidden",m!=="fixed_rest");document.getElementById("customDetails")?.classList.toggle("hidden",m!=="custom")}
function addExpenseFromModal(){const e=currentEvent(),title=document.getElementById("expenseTitle").value.trim(),amount=Number(document.getElementById("expenseAmount").value||0),mode=document.querySelector("input[name='splitMode']:checked")?.value||"equal";if(!title)return alert("Название расхода обязательно.");if(!amount||amount<=0)return alert("Впиши нормальную сумму.");const payers={};e.people.forEach(n=>{const checked=document.querySelector(`[data-payer-check="${css(n)}"]`)?.checked,paid=Number(document.querySelector(`[data-paid="${css(n)}"]`)?.value||0);if(checked&&paid>0)payers[n]=paid});const paidTotal=Object.values(payers).reduce((a,b)=>a+b,0);if(Math.round(paidTotal)!==Math.round(amount))return alert(`Плательщики внесли ${money(paidTotal)}, а расход ${money(amount)}. Должно совпасть.`);const participants=e.people.filter(n=>document.querySelector(`[data-participant="${css(n)}"]`)?.checked);if(!participants.length)return alert("Выбери участников расхода.");const shares=buildShares(e,participants,amount,mode);if(!shares)return;e.expenses.unshift({id:uid(),title,amount,payers,participants,splitMode:mode,shares,createdAt:new Date().toISOString()});save();closeModal();state.view="expenses";render()}
function buildShares(e,participants,amount,mode){const shares={};if(mode==="equal"){const each=amount/participants.length;participants.forEach(p=>shares[p]=each);return shares}if(mode==="fixed_rest"){let fixedTotal=0;participants.forEach(n=>{const checked=document.querySelector(`[data-fixed-check="${css(n)}"]`)?.checked,fixed=Number(document.querySelector(`[data-fixed="${css(n)}"]`)?.value||0);if(checked){shares[n]=fixed;fixedTotal+=fixed}});if(fixedTotal>amount){alert("Фиксированные суммы больше расхода.");return null}const restPeople=participants.filter(p=>!(p in shares));if(!restPeople.length&&Math.round(fixedTotal)!==Math.round(amount)){alert("Некому делить остаток.");return null}const each=restPeople.length?(amount-fixedTotal)/restPeople.length:0;restPeople.forEach(p=>shares[p]=each);return shares}if(mode==="custom"){let total=0;participants.forEach(n=>{const v=Number(document.querySelector(`[data-custom="${css(n)}"]`)?.value||0);shares[n]=v;total+=v});if(Math.round(total)!==Math.round(amount)){alert(`Суммы по людям дают ${money(total)}, а расход ${money(amount)}.`);return null}return shares}}
function calculateBalances(e){const b={};e.people.forEach(p=>b[p]=0);e.expenses.forEach(exp=>{Object.entries(exp.payers).forEach(([p,a])=>b[p]=(b[p]||0)+Number(a||0));Object.entries(exp.shares).forEach(([p,s])=>b[p]=(b[p]||0)-Number(s||0))});return b}
function calculateSettlements(e){const b=calculateBalances(e),debtors=[],creditors=[];Object.entries(b).forEach(([p,bal])=>{const r=Math.round(bal);if(r<0)debtors.push({person:p,amount:-r});if(r>0)creditors.push({person:p,amount:r})});debtors.sort((a,b)=>b.amount-a.amount);creditors.sort((a,b)=>b.amount-a.amount);const s=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const a=Math.min(debtors[i].amount,creditors[j].amount);if(a>0)s.push({from:debtors[i].person,to:creditors[j].person,amount:a});debtors[i].amount-=a;creditors[j].amount-=a;if(debtors[i].amount===0)i++;if(creditors[j].amount===0)j++}return s}
function renderEvents(){const html=state.events.length?state.events.map(e=>{const b=calculateBalances(e),you=e.people[0],main=you?b[you]||0:0;return `<article class="card event-card" onclick="openEvent('${e.id}')"><div class="poster">${e.poster||"🌴"}</div><div><h3 class="event-title">${safe(e.title)}</h3><div class="meta">${e.people.length} участников · ${e.expenses.length} расходов</div><div class="meta" style="color:var(--cyan)">Обновлено сегодня</div></div><div class="balance">${money(Math.abs(main))}<small>баланс</small></div></article>`}).join(""):`<div class="empty">Пока мероприятий нет. Нажми “Новое мероприятие”.</div>`;const g=getGlobalDebt();app.innerHTML=`<h2 class="section-title">Мои мероприятия</h2>${html}<section class="card stats-card"><div class="stats-grid"><div class="stat"><h3>Ты должен</h3><strong>${money(g.youOwe)}</strong><span class="meta">по всем мероприятиям</span></div><div class="stat"><h3>Тебе должны</h3><strong>${money(g.owedToYou)}</strong><span class="meta">по всем мероприятиям</span></div></div></section>`}
function renderExpenses(){const e=currentEvent();if(!e){app.innerHTML=`<div class="empty">Сначала создай мероприятие.</div>`;return}const html=e.expenses.length?e.expenses.map(exp=>`<article class="card expense-item"><div class="expense-icon">${guessIcon(exp.title)}</div><div><strong>${safe(exp.title)}</strong><small>${Object.keys(exp.payers).join(", ")} оплатил(и)</small></div><strong style="color:var(--acid)">${money(exp.amount)}</strong></article>`).join(""):`<div class="empty">Расходов пока нет. Добавь первый.</div>`;app.innerHTML=`<h2 class="section-title">${safe(e.title)}</h2><button class="acid-btn big" onclick="openAddExpenseModal()">+ Добавить расход</button><h2 class="section-title">Расходы</h2>${html}`}
function renderSummary(){const e=currentEvent();if(!e){app.innerHTML=`<div class="empty">Сначала создай мероприятие.</div>`;return}const s=calculateSettlements(e),b=calculateBalances(e);app.innerHTML=`<h2 class="section-title">Итоги: ${safe(e.title)}</h2><section class="card stats-card"><div class="stats-grid"><div class="stat"><h3>Людей</h3><strong>${e.people.length}</strong></div><div class="stat"><h3>Расходов</h3><strong>${e.expenses.length}</strong></div></div></section><h2 class="section-title">Кто кому должен</h2><section class="card">${s.length?s.map(x=>`<div class="summary-row"><span>${safe(x.from)} → ${safe(x.to)}</span><strong>${money(x.amount)}</strong></div>`).join(""):`<div class="empty">Пока долгов нет.</div>`}<button class="copy-btn" onclick="copySummary()">Экспорт в Telegram</button></section><h2 class="section-title">Балансы</h2><section class="card">${Object.entries(b).map(([p,bal])=>`<div class="summary-row"><span>${safe(p)}</span><strong style="color:${bal>=0?'var(--cyan)':'var(--pink)'}">${money(bal)}</strong></div>`).join("")}</section>`}
function renderSettings(){const e=currentEvent();app.innerHTML=`<h2 class="section-title">Настройки</h2><section class="card"><p class="empty">Данные хранятся локально в браузере. Пока без облака, без регистрации, без лишней бюрократии.</p><button class="secondary-btn" onclick="openNewEventModal()">Создать мероприятие</button>${e?`<button class="danger-btn" onclick="deleteCurrentEvent()">Удалить текущее мероприятие</button>`:""}</section>`}
function deleteCurrentEvent(){const e=currentEvent();if(!e)return;if(!confirm(`Удалить "${e.title}"?`))return;state.events=state.events.filter(x=>x.id!==e.id);state.activeEventId=state.events[0]?.id||null;state.view="events";save();render()}
function copySummary(){const e=currentEvent();if(!e)return;const s=calculateSettlements(e),text=[`Итог по ${e.title}:`,"",s.length?s.map(x=>`${x.from} должен ${x.to}: ${money(x.amount)}`).join("\\n"):"Долгов нет."].join("\\n");navigator.clipboard.writeText(text);alert("Скопировано")}
function getGlobalDebt(){let youOwe=0,owedToYou=0;state.events.forEach(e=>{const you=e.people[0];if(!you)return;const bal=calculateBalances(e)[you]||0;if(bal<0)youOwe+=Math.abs(bal);if(bal>0)owedToYou+=bal});return{youOwe,owedToYou}}
function guessIcon(t){t=t.toLowerCase();if(t.includes("мак")||t.includes("бургер"))return"🍔";if(t.includes("пиво")||t.includes("бар"))return"🍺";if(t.includes("такси"))return"🚕";if(t.includes("рест")||t.includes("август"))return"🍽️";if(t.includes("трав")||t.includes("шиш"))return"🌿";return"💸"}
function setView(v){state.view=v;save();render()}function updateNav(){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view))}
function render(){updateNav();if(state.view==="events")renderEvents();if(state.view==="expenses")renderExpenses();if(state.view==="summary")renderSummary();if(state.view==="settings")renderSettings()}
document.getElementById("newEventBtn").addEventListener("click",openNewEventModal);document.getElementById("closeModalBtn").addEventListener("click",closeModal);document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});document.getElementById("resetBtn").addEventListener("click",()=>{if(confirm("Стереть все данные?")){localStorage.removeItem(STORAGE_KEY);state={events:[],activeEventId:null,view:"events"};render()}});document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js")}render();
